/* Second vocabulary expansion (toward ~1,800 words for A2): high-frequency
   words from a Polish subtitle frequency list (OpenSubtitles 2018) that the
   course lacked, plus the topic words of the adult A1/A2 standard
   (work, offices, health, media, environment, feelings). Appended to each
   unit after EXTRA_VOCAB, so existing flashcard ids never change. */
const EXTRA_VOCAB_2 = {
  0: [
    ["tylko","only, just"],
    ["naprawdę","really"],
    ["właśnie","just, exactly"],
    ["prawda?","right? isn't it?"],
    ["no","well, yeah (spoken)","No, jasne! = Yeah, sure!"],
    ["spoko","cool, fine (casual)"],
    ["dzięki","thanks (casual)"],
    ["hej","hey, hi"],
    ["Nie ma sprawy.","No problem."],
    ["W porządku.","All right. / OK."],
    ["Wszystko w porządku?","Is everything OK?"],
    ["Powodzenia!","Good luck!"],
    ["Gratulacje!","Congratulations!"],
    ["Jasne!","Sure!"],
    ["Racja.","That's right."],
    ["Miłego dnia!","Have a nice day!"],
    ["Nawzajem!","Likewise!"],
    ["Przepraszam, że przeszkadzam.","Sorry to bother you."],
    ["Nic nie szkodzi.","No harm done. / It doesn't matter."]
  ],
  1: [
    ["ojciec","father","gen. ojca"],
    ["matka","mother"],
    ["teść / teściowa","father-in-law / mother-in-law"],
    ["szwagier / szwagierka","brother-in-law / sister-in-law"],
    ["bliźniaki","twins"],
    ["krewny / krewna","relative (m / f)"],
    ["znajomy / znajoma","acquaintance, friend (m / f)"],
    ["sąsiad / sąsiadka","neighbour (m / f)"],
    ["małżeństwo","marriage; married couple"],
    ["ślub","wedding (ceremony)"],
    ["wesele","wedding reception","⚠ SR veselje = joy, party"],
    ["kochanie","darling"],
    ["dorastać","to grow up"],
    ["urodzić się","to be born","Urodziłem się w Nišu."],
    ["zmarły","deceased"],
    ["wdowa / wdowiec","widow / widower"],
    ["samotny","single; lonely"],
    ["mieszkać razem","to live together"]
  ],
  2: [
    ["dwadzieścia jeden","21"],
    ["raz","once; one time","dwa razy = twice"],
    ["pierwszy","first"],
    ["drugi","second"],
    ["trzeci","third"],
    ["ostatni","last"],
    ["następny","next"],
    ["połowa","half (noun)"],
    ["parę","a couple of"],
    ["wiele","many, much"],
    ["wszystko","everything"],
    ["nic","nothing","Nic nie wiem."],
    ["nikt","nobody","Nikt nie przyszedł."],
    ["ktoś","somebody"],
    ["coś","something"],
    ["policzyć","to count (perf.)"]
  ],
  3: [
    ["śmietanka","cream (for coffee)"],
    ["kakao","cocoa"],
    ["wino","wine"],
    ["woda gazowana","sparkling water"],
    ["woda niegazowana","still water"],
    ["rogalik","croissant"],
    ["pączek","doughnut"],
    ["filiżanka","cup (with saucer)"],
    ["kubek","mug"],
    ["Czy mogę zapłacić kartą?","Can I pay by card?"],
    ["Poproszę jeszcze jedno.","Another one, please."]
  ],
  4: [
    ["pomagać","to help (+ dative)","perf. pomóc"],
    ["znaleźć","to find (perf.)","znajdę; znalazłem"],
    ["próbować","to try","perf. spróbować"],
    ["używać","to use (+ genitive)"],
    ["działać","to work, function","Telefon nie działa."],
    ["żyć","to live, be alive","żyję, żyjesz"],
    ["siedzieć","to sit (be sitting)"],
    ["stać","to stand","stoję, stoisz"],
    ["leżeć","to lie (be lying)"],
    ["patrzeć","to look (at)","patrzę na…"],
    ["słyszeć","to hear"],
    ["czuć","to feel; to smell","czuję"],
    ["brać","to take","biorę, bierzesz"],
    ["dawać","to give","daję, dajesz"],
    ["kupować","to buy (regularly)","kupuję"],
    ["prowadzić","to lead; to run (a business)"],
    ["porozmawiać","to have a talk","z + instrumental"],
    ["uwierzyć","to believe (perf.)"],
    ["znaczyć","to mean","Co to znaczy?"],
    ["oznaczać","to mean, signify"],
    ["brzmieć","to sound","To brzmi dobrze."],
    ["trzymać","to hold","trzymam"],
    ["zostawić","to leave (something)","zostawiać"],
    ["zabrać","to take (away, along)","zabiorę"],
    ["przestać","to stop (doing)","przestanę; Przestań!"],
    ["chronić","to protect"],
    ["walczyć","to fight"],
    ["uciec","to run away, escape","uciekać"],
    ["spaść","to fall","spadać"],
    ["rosnąć","to grow"],
    ["kłamać","to lie (tell lies)","kłamię"],
    ["żartować","to joke","Żartujesz!"],
    ["mieć rację","to be right"],
    ["mieć szczęście","to be lucky"],
    ["mieć pecha","to be unlucky"],
    ["mieć ochotę na","to feel like (+ accusative)","Mam ochotę na kawę."]
  ],
  5: [
    ["wieś","village; countryside","na wsi"],
    ["budynek","building"],
    ["okolica","area, neighbourhood"],
    ["niedaleko","not far (from)"],
    ["wszędzie","everywhere"],
    ["nigdzie","nowhere","Nigdzie nie idę."],
    ["gdzieś","somewhere"],
    ["w środku","inside"],
    ["na zewnątrz","outside"],
    ["centrum handlowe","shopping centre"],
    ["ratusz","town hall"],
    ["dzielnica","district"],
    ["przedmieście","suburb"],
    ["miejsce","place; seat","SR mesto"],
    ["adres zamieszkania","home address"]
  ],
  6: [
    ["uwielbiać","to love, adore","Uwielbiam pierogi."],
    ["hobby","hobby"],
    ["gra","game"],
    ["mecz","match (sport)"],
    ["piłka","ball"],
    ["czytanie","reading"],
    ["fotografia","photography"],
    ["rysować","to draw"],
    ["malować","to paint"],
    ["szynka","ham"],
    ["kiełbasa","sausage"],
    ["ogórek","cucumber"],
    ["pomidor","tomato"],
    ["gruszka","pear"],
    ["winogrona","grapes"],
    ["słodycze","sweets"],
    ["słodki","sweet"],
    ["kwaśny","sour"],
    ["jagody","blueberries","⚠ SR jagode = strawberries (PL truskawki)"]
  ],
  7: [
    ["wtedy","then, at that time"],
    ["zaraz","in a moment"],
    ["wkrótce","soon"],
    ["niedługo","soon, before long"],
    ["dawno","a long time ago"],
    ["niedawno","recently"],
    ["czasem","sometimes"],
    ["rzadko","rarely"],
    ["od razu","straight away"],
    ["natychmiast","immediately"],
    ["za chwilę","in a moment"],
    ["chwila","a moment","Chwileczkę!"],
    ["moment","moment"],
    ["sekunda","second"],
    ["dziś","today"],
    ["weekend","weekend","w weekend"]
  ],
  8: [
    ["ważny","important"],
    ["prawdziwy","real, true"],
    ["dziwny","strange"],
    ["prosty","simple; straight"],
    ["wolny","free; slow"],
    ["zajęty","busy, occupied"],
    ["pełny","full"],
    ["pusty","empty"],
    ["czysty","clean"],
    ["brudny","dirty"],
    ["cichy","quiet"],
    ["głośny","loud"],
    ["bezpieczny","safe"],
    ["niebezpieczny","dangerous"],
    ["gotowy","ready"],
    ["możliwy","possible"],
    ["potrzebny","needed"],
    ["własny","own"],
    ["różny","various, different"],
    ["jedyny","the only"],
    ["świeży","fresh"],
    ["czerstwy","stale (bread)","⚠ SR čvrst = firm"]
  ],
  9: [
    ["wejść / wchodzić","to go in, enter","do + genitive"],
    ["wyjść / wychodzić","to go out, leave","z + genitive"],
    ["przyjechać / przyjeżdżać","to arrive (by vehicle)"],
    ["wyjechać / wyjeżdżać","to leave (by vehicle)"],
    ["dojść / dochodzić","to reach (on foot)"],
    ["dojechać / dojeżdżać","to get to (by vehicle)"],
    ["pójść","to go (once, on foot)","pójdę"],
    ["przejść / przechodzić","to cross, walk across"],
    ["skręcić / skręcać","to turn","skręć w lewo"],
    ["z powrotem","back"],
    ["samochodem","by car"],
    ["droga","road; way"],
    ["autostrada","motorway"],
    ["korek","traffic jam"],
    ["kierunek","direction"]
  ],
  10: [
    ["supermarket","supermarket"],
    ["targ","(open-air) market"],
    ["klient / klientka","customer (m / f)"],
    ["za darmo","for free"],
    ["zniżka","discount"],
    ["wyprzedaż","sale"],
    ["gotówka","cash","płacić gotówką"],
    ["portfel","wallet"],
    ["przymierzalnia","fitting room"],
    ["zwrot","return, refund"],
    ["reklamacja","complaint (about a product)"],
    ["otwarty","open"],
    ["zamknięty","closed"],
    ["koszyk","basket"],
    ["wózek","trolley; pushchair"],
    ["Ile płacę?","How much do I pay?"],
    ["Reszty nie trzeba.","Keep the change."]
  ],
  11: [
    ["zeszły","last (week, year)","w zeszłym roku"],
    ["festiwal","festival"],
    ["wystawa","exhibition"],
    ["spędzić","to spend (time)","spędzać"],
    ["odpocząć","to rest (perf.)"],
    ["bawić się","to have fun; to play"],
    ["Jak było?","How was it?"],
    ["Co słychać?","What's new?"],
    ["zdarzyć się","to happen","Co się stało?"],
    ["stać się","to happen; to become"],
    ["zrobiłem / zrobiłam","I did (m / f)"],
    ["powiedziałem / powiedziałam","I said (m / f)"],
    ["wróciłem / wróciłam","I came back (m / f)"],
    ["przyszedłem / przyszłam","I came (m / f)"],
    ["zobaczyłem / zobaczyłam","I saw (m / f)"]
  ],
  12: [
    ["pensja","salary"],
    ["wypłata","pay, payout"],
    ["zwolnienie lekarskie","sick leave"],
    ["rozmowa kwalifikacyjna","job interview"],
    ["CV","CV"],
    ["doświadczenie","experience"],
    ["kandydat","candidate"],
    ["zatrudnić","to employ, hire"],
    ["zwolnić","to dismiss, fire; to slow down"],
    ["na pełny etat","full-time"],
    ["na pół etatu","part-time"],
    ["zmiana","shift; change"],
    ["nadgodziny","overtime"],
    ["zebranie","meeting (at work)"],
    ["projekt","project"],
    ["zadanie","task"],
    ["termin","deadline; appointment"],
    ["wolne","time off"],
    ["kolega z pracy","colleague"],
    ["praca zdalna","remote work"]
  ],
  13: [
    ["należy","one should (formal)"],
    ["zabronione","forbidden"],
    ["Zakaz parkowania","No parking"],
    ["ostrożnie","carefully"],
    ["prawo jazdy","driving licence"],
    ["zasada","rule"],
    ["mandat","fine (penalty)"],
    ["kara","punishment, penalty"],
    ["pozwolenie","permission, permit"],
    ["dać radę","to manage, cope","Dam radę!"],
    ["Nie dam rady.","I can't make it."],
    ["udać się","to succeed (it works out)","Udało mi się!"],
    ["obowiązek","duty, obligation"],
    ["możliwość","possibility"],
    ["Czy mogę wejść?","May I come in?"],
    ["Nie wolno tu parkować.","You can't park here."]
  ],
  14: [
    ["człowiek / ludzie","person / people"],
    ["dziecko / dzieci","child / children"],
    ["mężczyzna","man","pl. mężczyźni"],
    ["kobieta","woman"],
    ["chłopiec","boy","pl. chłopcy"],
    ["dziewczynka","little girl"],
    ["oko / oczy","eye / eyes"],
    ["ucho / uszy","ear / ears"],
    ["ręka / ręce","hand / hands","⚠ SR reka = river"],
    ["rok / lata","year / years"],
    ["pies / psy","dog / dogs","⚠ SR pas = dog; PL pas = belt"],
    ["przyjaciel / przyjaciele","friend / friends"],
    ["tysiące","thousands"],
    ["milion","million"],
    ["mnóstwo","loads of (+ genitive)"],
    ["większość","most, the majority"],
    ["część","part"],
    ["kilkoro","several (children)"]
  ],
  15: [
    ["rozbierać się","to get undressed"],
    ["jeść śniadanie","to have breakfast"],
    ["iść do pracy","to go to work"],
    ["wracać do domu","to come home"],
    ["odkurzać","to vacuum"],
    ["robić pranie","to do the washing"],
    ["iść na zakupy","to go shopping"],
    ["czuć się","to feel","Jak się czujesz?"],
    ["przypominać","to remind","perf. przypomnieć"],
    ["martwić się","to worry"],
    ["cieszyć się","to be glad","Cieszę się!"],
    ["denerwować się","to get nervous, annoyed"],
    ["umawiać się","to arrange to meet"],
    ["śnić","to dream (in sleep)"],
    ["sen","sleep; dream"],
    ["zazwyczaj","usually"]
  ],
  16: [
    ["morze","sea","nad morzem"],
    ["góry","mountains","w górach"],
    ["opalać się","to sunbathe"],
    ["wypoczywać","to rest, holiday"],
    ["pokój jednoosobowy","single room"],
    ["pokój dwuosobowy","double room"],
    ["śniadanie wliczone","breakfast included"],
    ["odwołać","to cancel"],
    ["zamierzać","to intend"],
    ["mieć zamiar","to plan to, intend"],
    ["pewnie","probably"],
    ["wybierać się","to be going (to)","Wybieram się do Gdańska."],
    ["podróżować","to travel"]
  ],
  17: [
    ["słyszeć / usłyszeć","to hear"],
    ["myć / umyć","to wash"],
    ["sprzątać / posprzątać","to tidy"],
    ["szukać / znaleźć","to look for / to find"],
    ["próbować / spróbować","to try"],
    ["zapominać / zapomnieć","to forget","⚠ SR zapamtiti = to remember (PL zapamiętać)"],
    ["przypominać / przypomnieć","to remind"],
    ["decydować / zdecydować","to decide"],
    ["wybierać / wybrać","to choose","wybiorę"],
    ["zmieniać / zmienić","to change"],
    ["rozumieć / zrozumieć","to understand"],
    ["budować / zbudować","to build"],
    ["tracić / stracić","to lose (time, money)"],
    ["wygrywać / wygrać","to win"],
    ["przegrywać / przegrać","to lose (a game)"],
    ["odpoczywać / odpocząć","to rest","odpocznę"],
    ["przygotowywać / przygotować","to prepare"],
    ["załatwiać / załatwić","to sort out, arrange"],
    ["dostawać / dostać","to get, receive","dostanę"],
    ["zostawać / zostać","to stay; to become","zostanę"],
    ["siadać / usiąść","to sit down","usiądę"],
    ["kłaść / położyć","to put (lying)","położę"],
    ["wkładać / włożyć","to put in; to put on (clothes)"],
    ["zdejmować / zdjąć","to take off","zdejmę"],
    ["podawać / podać","to pass, hand"],
    ["wynajmować / wynająć","to rent","wynajmę"],
    ["umierać / umrzeć","to die"],
    ["pożyczać / pożyczyć","to lend; to borrow"],
    ["gubić / zgubić","to lose (misplace)"]
  ],
  18: [
    ["pasować","to suit, fit (+ dative)"],
    ["wydawać się","to seem (+ dative)","Wydaje mi się, że…"],
    ["chodzić o","to be about","O co chodzi?"],
    ["opłacać się","to be worth it"],
    ["przeszkadzać","to bother (+ dative)"],
    ["gratulować","to congratulate (+ dative)"],
    ["odpowiadać","to suit (+ dative); to answer","Ten termin mi odpowiada."],
    ["Szkoda!","What a pity!"],
    ["Brawo!","Well done!"],
    ["Smutno mi.","I'm sad."],
    ["Wstyd mi.","I'm ashamed."],
    ["Głupio mi.","I feel awkward."],
    ["Wygodnie mi.","I'm comfortable."],
    ["Jest mi dobrze.","I feel good here."],
    ["pomóc komuś","to help someone (+ dative)"],
    ["prezent dla…","a present for…"],
    ["perfumy","perfume","plural only"],
    ["czekoladki","chocolates"],
    ["dziękuję za…","thank you for… (+ acc.)"],
    ["składać życzenia","to give one's wishes"],
    ["pożyczyć komuś","to lend someone"],
    ["obiecać komuś","to promise someone"],
    ["wysłać komuś","to send someone"],
    ["pokazać komuś","to show someone"],
    ["powiedzieć komuś","to tell someone"],
    ["kupić komuś","to buy (for) someone"],
    ["mojemu bratu","to my brother (dative)"],
    ["mojej siostrze","to my sister (dative)"],
    ["dzieciom","to the children (dative)"]
  ],
  19: [
    ["Uważaj!","Be careful!"],
    ["Pokaż!","Show me!"],
    ["Weź!","Take it!"],
    ["Zrób to!","Do it!"],
    ["Przestań!","Stop it!"],
    ["Spokojnie!","Calm down! / Easy!"],
    ["Patrz!","Look!"],
    ["Zadzwoń!","Call (me)!"],
    ["Napisz!","Write (to me)!"],
    ["Otwórz!","Open (it)!"],
    ["Zamknij!","Close (it)!"],
    ["Wejdź!","Come in!"],
    ["Wyjdź!","Get out!"],
    ["Siadaj!","Sit down! (informal)"],
    ["Proszę poczekać.","Please wait."],
    ["Proszę wejść.","Please come in."],
    ["Proszę podpisać.","Please sign."],
    ["Proszę się nie martwić.","Please don't worry."],
    ["Niech pani usiądzie.","Please sit down (to a woman)."],
    ["Pomocy!","Help!"],
    ["Nie rób tego!","Don't do that!"],
    ["Nie zapomnij!","Don't forget!"],
    ["Nie spóźnij się!","Don't be late!"],
    ["Bądź cicho!","Be quiet!"],
    ["Miej oko na…","Keep an eye on…"],
    ["Proszę mi pokazać…","Please show me…"],
    ["Przepraszam, którędy do…?","Excuse me, which way to…?"],
    ["Proszę skręcić w lewo.","Please turn left."],
    ["Proszę iść prosto.","Please go straight on."]
  ],
  20: [
    ["zdanie","opinion; sentence","moim zdaniem"],
    ["opinia","opinion"],
    ["uważać","to think; to be careful","⚠ SR uvažavati = respect. Uważam, że…"],
    ["sądzić","to think, judge"],
    ["Wydaje mi się, że…","It seems to me that…"],
    ["według mnie","in my view"],
    ["z jednej strony","on the one hand"],
    ["z drugiej strony","on the other hand"],
    ["zaleta","advantage"],
    ["wada","disadvantage, flaw"],
    ["różnica","difference"],
    ["mniej","less"],
    ["coraz","more and more","coraz lepiej"],
    ["prawie","almost"],
    ["zupełnie","completely"],
    ["całkiem","quite, entirely"],
    ["raczej","rather"],
    ["dość","quite; enough"],
    ["zbyt","too","zbyt drogi"],
    ["najlepiej","best (adverb)"],
    ["najgorzej","worst (adverb)"],
    ["najczęściej","most often"],
    ["ulubiony","favourite"],
    ["łatwiejszy","easier"],
    ["trudniejszy","more difficult"],
    ["ciekawszy","more interesting"],
    ["szybszy","faster"],
    ["wolniejszy","slower"],
    ["nowocześniejszy","more modern"],
    ["Zgadzam się z tobą.","I agree with you."],
    ["To zależy.","It depends."],
    ["Zależy od…","It depends on… (+ genitive)"],
    ["pomysł","idea"],
    ["sposób","way, method"],
    ["problem","problem"],
    ["sprawa","matter, issue"],
    ["pytanie","question"],
    ["odpowiedź","answer"],
    ["powód","reason"],
    ["życie","life"],
    ["koniec","end","⚠ SR kraj = end"],
    ["początek","beginning"],
    ["historia","history; story"],
    ["miłość","love"],
    ["szczęście","happiness; luck"],
    ["sytuacja","situation"],
    ["decyzja","decision"],
    ["błąd","mistake","pl. błędy"],
    ["wybór","choice"],
    ["cel","goal, aim"],
    ["informacja","information"],
    ["fakt","fact"],
    ["przypadek","case; chance","przypadkiem = by chance"],
    ["sens","sense, point","To nie ma sensu."],
    ["ryzyko","risk"]
  ],
  21: [
    ["Europa","Europe"],
    ["świat","world","na świecie"],
    ["granica","border","za granicą = abroad"],
    ["cudzoziemiec / cudzoziemka","foreigner (m / f)"],
    ["wiza","visa"],
    ["karta pobytu","residence card"],
    ["pochodzić z","to come from","Pochodzę z Serbii."],
    ["Belgrad","Belgrade","w Belgradzie"],
    ["Czechy","Czech Republic","plural: w Czechach"],
    ["Słowacja","Slovakia"],
    ["Węgry","Hungary","plural: na Węgrzech"],
    ["Grecja","Greece"],
    ["Austria","Austria"],
    ["Rosja","Russia"],
    ["Bośnia","Bosnia"],
    ["Czarnogóra","Montenegro"],
    ["Macedonia Północna","North Macedonia"],
    ["Bułgaria","Bulgaria"],
    ["Rumunia","Romania"],
    ["serbski","Serbian (language, adj.)"],
    ["po serbsku","in Serbian"],
    ["imię i nazwisko","full name"],
    ["stan cywilny","marital status (on forms)"],
    ["wolny / wolna","single (on forms)"]
  ],
  22: [
    ["szczęśliwy","happy"],
    ["zdenerwowany","upset, nervous"],
    ["zadowolony","pleased, satisfied"],
    ["zakochany","in love"],
    ["głodny","hungry"],
    ["spragniony","thirsty"],
    ["uprzejmy","polite"],
    ["głupi","stupid, silly"],
    ["odważny","brave"],
    ["nieśmiały","shy"],
    ["zabawny","funny"],
    ["poważny","serious"],
    ["uczciwy","honest"],
    ["cierpliwy","patient"],
    ["wąsy","moustache"],
    ["wzrost","height"],
    ["twarz","face","SR lice"],
    ["płakać","to cry","płaczę"],
    ["śmiać się","to laugh","śmieję się"],
    ["krzyczeć","to shout"],
    ["całować","to kiss"],
    ["przytulić","to hug"],
    ["kłócić się","to argue"],
    ["przepraszać","to apologise","perf. przeprosić"],
    ["wybaczyć","to forgive"],
    ["bać się","to be afraid (+ genitive)","Boję się psów."],
    ["wstydzić się","to be ashamed"],
    ["tęsknić za","to miss (+ instrumental)","Tęsknię za domem."],
    ["zależeć","to matter (+ dative)","Zależy mi na tym."],
    ["złość","anger"],
    ["radość","joy"],
    ["strach","fear"]
  ],
  23: [
    ["plasterek","a slice"],
    ["paczka","packet; parcel"],
    ["pudełko","box"],
    ["torba","bag"],
    ["brakować","to be missing, lack (+ genitive)","Brakuje mi czasu."],
    ["ani… ani…","neither… nor…"],
    ["oprócz","except, apart from (+ genitive)"],
    ["zamiast","instead of (+ genitive)"],
    ["podczas","during (+ genitive)"],
    ["według","according to (+ genitive)"],
    ["wzdłuż","along (+ genitive)"],
    ["olej","oil"],
    ["mąka","flour"]
  ],
  24: [
    ["chmura","cloud"],
    ["burza","storm"],
    ["mgła","fog"],
    ["mróz","frost"],
    ["upał","heatwave, heat"],
    ["temperatura","temperature"],
    ["pochmurno","cloudy"],
    ["słonecznie","sunny"],
    ["Szczęśliwego Nowego Roku!","Happy New Year!"],
    ["Sto lat!","Happy birthday! (a hundred years)"],
    ["dzień wolny","day off"],
    ["Wigilia","Christmas Eve"],
    ["rocznica","anniversary"]
  ],
  25: [
    ["klucz","key"],
    ["ściana","wall"],
    ["podłoga","floor (surface)"],
    ["sufit","ceiling"],
    ["meble","furniture"],
    ["zmywarka","dishwasher"],
    ["zasłony","curtains"],
    ["poduszka","pillow"],
    ["kołdra","duvet"],
    ["gniazdko","socket"],
    ["kran","tap"],
    ["prysznic","shower"]
  ],
  26: [
    ["odprawa","check-in"],
    ["przylot","arrival (plane)"],
    ["odlot","departure (plane)"],
    ["w jedną stronę","one-way"],
    ["ulgowy","reduced (ticket)"],
    ["normalny","full-price (ticket); normal"],
    ["konduktor","conductor"],
    ["miejsce przy oknie","window seat"],
    ["podróżny","traveller, passenger"]
  ],
  27: [
    ["zdrowie","health"],
    ["choroba","illness"],
    ["ból","pain"],
    ["lek","medicine"],
    ["pogotowie","emergency service"],
    ["karetka","ambulance"],
    ["dentysta / dentystka","dentist"],
    ["ubezpieczenie","insurance"],
    ["badanie","examination, test"],
    ["wynik","result"],
    ["ciśnienie","blood pressure"],
    ["alergia","allergy"],
    ["złamać","to break (a bone)"],
    ["skaleczyć się","to cut oneself"],
    ["ćwiczyć","to exercise; to practise"],
    ["trening","training session"],
    ["zdrowo","healthily"],
    ["dieta","diet"],
    ["waga","weight; scales"],
    ["schudnąć","to lose weight"],
    ["rzucić palenie","to quit smoking"],
    ["Na zdrowie!","Cheers! / Bless you!"]
  ],
  28: [
    ["jednak","however"],
    ["chociaż","although"],
    ["mimo że","even though"],
    ["natomiast","whereas, on the other hand"],
    ["poza tym","besides"],
    ["na przykład","for example"],
    ["czyli","that is, so"],
    ["to znaczy","that means, I mean"],
    ["ponieważ","because (formal)"],
    ["jeśli / jeżeli","if"],
    ["zanim","before (+ clause)"],
    ["dopóki","as long as; until"],
    ["odkąd","since (+ clause)"],
    ["nawet","even"],
    ["także","also"],
    ["również","also (formal)"],
    ["przecież","after all, but (surely)"],
    ["właściwie","actually"],
    ["w ogóle","at all; in general"],
    ["wreszcie","at last"],
    ["w końcu","finally; after all"],
    ["na końcu","at the end"],
    ["poważnie","seriously"],
    ["szczerze","honestly","szczerze mówiąc"],
    ["dokładnie","exactly"],
    ["mocno","strongly, hard"],
    ["łatwo","easily"],
    ["trudno","it's hard; with difficulty"],
    ["możliwe","possibly; it's possible"],
    ["wystarczy","that's enough; it's enough to…"],
    ["ledwo","barely"],
    ["akurat","just, exactly then"]
  ],
  29: [
    ["karta dań","menu"],
    ["zupa dnia","soup of the day"],
    ["zamówienie","order"],
    ["wegański","vegan"],
    ["polecić / polecać","to recommend"],
    ["Co pan poleca?","What do you recommend? (to a man)"],
    ["Czy mogę prosić o…?","Could I have…? (+ accusative)"],
    ["Czy jest coś bez mięsa?","Is there anything without meat?"],
    ["Wolałbym…","I'd rather… (m)"],
    ["Wolałabym…","I'd rather… (f)"],
    ["marzenie","dream (wish)"],
    ["gdybym","if I (were / had)","Gdybym miał czas, …"],
    ["Czy byłby pan tak miły…?","Would you be so kind… (to a man)?"],
    ["porcja","portion"],
    ["dodatki","side dishes"],
    ["surówka","salad (side, raw veg)"],
    ["ziemniaki puree","mashed potatoes"],
    ["frytki","chips, fries"],
    ["kotlet schabowy","breaded pork cutlet"],
    ["pierogi","dumplings"],
    ["barszcz","beetroot soup"],
    ["żurek","sour rye soup"],
    ["gołąbki","cabbage rolls"],
    ["bigos","hunter's stew"],
    ["Czy to jest ostre?","Is it spicy?"],
    ["Rachunek, proszę.","The bill, please."],
    ["Smakowało?","Did you enjoy it?"],
    ["Było pyszne.","It was delicious."]
  ],
  30: [
    ["Szanowny Panie!","Dear Sir (formal letter)"],
    ["Szanowna Pani!","Dear Madam (formal letter)"],
    ["Pozdrawiam serdecznie","Warm regards"],
    ["Polki","Polish women"],
    ["Serbowie","Serbs (men / mixed)"],
    ["goście","guests"],
    ["sąsiedzi","neighbours (men / mixed)"],
    ["przyjaciele","friends"],
    ["dwaj","two (men)","dwaj bracia = dwóch braci"],
    ["trzej","three (men)"],
    ["obaj","both (men)"],
    ["obie","both (women / things)"],
    ["oboje","both (a man and a woman)"],
    ["którzy","who, which (men, plural)"],
    ["ci ludzie","these people"],
    ["moi rodzice","my parents"],
    ["nasi goście","our guests"],
    ["byli / były","they were (men / others)"],
    ["mieli / miały","they had (men / others)"],
    ["poszli / poszły","they went (men / others)"],
    ["Panie doktorze!","Doctor! (calling a man)"],
    ["Pani profesor!","Professor! (calling a woman)"]
  ],
  31: [
    ["odebrać (telefon)","to answer (the phone)"],
    ["oddzwonić","to call back"],
    ["nagrać się","to leave a message"],
    ["SMS","text message"],
    ["połączenie","connection; call"],
    ["rozłączyć się","to hang up"],
    ["zasięg","signal (coverage)"],
    ["bateria","battery"],
    ["ładowarka","charger"],
    ["aplikacja","app"],
    ["hasło","password"],
    ["zalogować się","to log in"],
    ["wysłać","to send"],
    ["pobrać","to download"],
    ["załącznik","attachment"],
    ["wideo","video"],
    ["media społecznościowe","social media"],
    ["program","programme"],
    ["reklama","advert"],
    ["Kto mówi?","Who's speaking?"],
    ["Proszę zostawić wiadomość.","Please leave a message."],
    ["Źle cię słyszę.","I can't hear you well."],
    ["Pomyłka.","Wrong number."],
    ["Zaraz oddzwonię.","I'll call you right back."],
    ["Czy mogę mówić z…?","Can I speak to…? (+ instrumental)"],
    ["Niestety nie mogę.","Unfortunately I can't."],
    ["Chętnie przyjdę!","I'd love to come!"],
    ["impreza urodzinowa","birthday party"],
    ["Co u ciebie?","How are you doing? What's new with you?"],
    ["Dawno się nie widzieliśmy!","Long time no see!"],
    ["Odezwij się!","Get in touch!"],
    ["Daj znać.","Let me know."],
    ["Nie ma mnie w domu.","I'm not at home."],
    ["Jestem w drodze.","I'm on my way."],
    ["Spóźnię się kilka minut.","I'll be a few minutes late."],
    ["Przepraszam, nie mogę rozmawiać.","Sorry, I can't talk."],
    ["Napisz mi SMS-a.","Text me."]
  ],
  32: [
    ["dokument","document"],
    ["zaświadczenie","certificate (official)"],
    ["podpisać","to sign"],
    ["wypełnić","to fill in","wypełnić formularz"],
    ["urzędnik / urzędniczka","clerk, official (m / f)"],
    ["PESEL","Polish ID number (like JMBG)"],
    ["meldunek","residence registration","SR prijava boravka"],
    ["zameldować się","to register one's address"],
    ["przesyłka","consignment, delivery"],
    ["odebrać","to collect, pick up"],
    ["wypłacić","to withdraw (money)"],
    ["wpłacić","to pay in"],
    ["opłata","fee"],
    ["umowa najmu","tenancy agreement"],
    ["naprawa","repair"],
    ["awaria","breakdown, fault"],
    ["hydraulik","plumber"],
    ["elektryk","electrician"],
    ["Gdzie mogę załatwić…?","Where can I sort out…?"],
    ["Jakie dokumenty są potrzebne?","Which documents are needed?"],
    ["termin ważności","expiry date"],
    ["prośba","request"],
    ["pomoc","help"],
    ["porada","advice"],
    ["zgoda","consent; agreement"],
    ["skarga","complaint"],
    ["Chciałbym złożyć reklamację.","I'd like to make a complaint (m)."]
  ],
  33: [
    ["przyroda","nature"],
    ["środowisko","environment"],
    ["góra","mountain"],
    ["wyspa","island"],
    ["park narodowy","national park"],
    ["łąka","meadow"],
    ["zwierzę","animal","pl. zwierzęta"],
    ["ptak","bird"],
    ["koń","horse"],
    ["krowa","cow"],
    ["zanieczyszczenie","pollution"],
    ["śmieci","rubbish"],
    ["segregować śmieci","to sort rubbish for recycling"],
    ["recykling","recycling"],
    ["oszczędzać","to save (water, money)"],
    ["klimat","climate"],
    ["ekologiczny","eco-friendly"],
    ["katedra","cathedral"],
    ["pamiątka","souvenir"],
    ["zwiedzanie","sightseeing"],
    ["widok","view"],
    ["szlak","(hiking) trail"],
    ["schronisko","mountain hut; animal shelter"],
    ["wschód / zachód słońca","sunrise / sunset"],
    ["północ","north; midnight"],
    ["południe","south; noon"],
    ["wschód","east"],
    ["zachód","west"],
    ["przez","for (a time); through","przez tydzień"],
    ["od dawna","for a long time"],
    ["nigdy wcześniej","never before"],
    ["kiedykolwiek","ever"],
    ["Byłeś kiedyś w…?","Have you ever been to…?"]
  ]
};
